### ISSUE TITLE
signment-2:  Prime Number 

### ISSUE THREAD

**Issue by 55bit23** [vtcbca/basic-programming-55bit23#3]
how can i make a Prime Number Checker

**Comment by 55bit23** [comment]
Using a Loop (Simple Approach):
This method checks divisors from 2 to 𝑛

**Comment by 59bit23** [comment]
Using a Loop (Simple Approach):
This method checks divisors from 2 to 𝑛

**Comment by 55bit23** [comment]
What data type is used for the number in a prime checker program?

**Comment by 59bit23** [comment]
The number is usually an integer (int) data

**Comment by 55bit23** [comment]
Can a prime number program handle floating-point numbers?

**Comment by 59bit23** [comment]
No, a prime checker typically works with integers. Floating-point numbers should be converted to integers first.

**Comment by 55bit23** [comment]
What is the smallest number you can check for primality?

**Comment by 59bit23** [comment]
The smallest number to check is 2, as numbers ≤1 are not prime.

**Comment by 55bit23** [comment]
How do you input a number in the program?

**Comment by 59bit23** [comment]
ou can use the input() function:

`num = int(input("Enter a number: "))`

**Comment by 55bit23** [comment]
thanks @59bit23 for sloveing my problems.
