### ISSUE TITLE
Fibonacci Sequence Generator

### ISSUE THREAD

**Issue by 44bit23** [vtcbca/basic-programming-55bit23#4]
Can the Fibonacci sequence be generated using recursion?

**Comment by 55bit23** [comment]
@44bit23  Yes, but recursion can be inefficient for large sequences.

**Comment by 44bit23** [comment]
What happens if you provide negative input for generating the sequence?

**Comment by 55bit23** [comment]
You should handle this with a condition to display a message like: "Please enter a positive number."

**Comment by 44bit23** [comment]
How do you calculate the nth Fibonacci number?

**Comment by 55bit23** [comment]
Use either an iterative loop, recursion, or a mathematical formula.

**Comment by 44bit23** [comment]
How do you store the Fibonacci sequence in Python?

**Comment by 55bit23** [comment]
Use a list to store the generated numbers.

**Comment by 44bit23** [comment]
wich datatype i  can use in Fibonacci Sequence Generator program

**Comment by 55bit23** [comment]
For a Fibonacci Sequence Generator, you can use :
int :To store individual Fibonacci numbers (e.g., 0, 1, 2, 3).

**Comment by 44bit23** [comment]
i got you @55bit23
