### ISSUE TITLE
Assignment 6-  Pattern of *

### ISSUE THREAD

**Issue by 52bit23** [vtcbca/basic-programming-55bit23#5]
Can this program work with negative numbers?

**Comment by 55bit23** [comment]
No, negative numbers should be avoided or handled with a message like "Enter a positive number."

**Comment by 52bit23** [comment]
How can you print the stars on the same line?

**Comment by 55bit23** [comment]
Use print('*', end=' ') to avoid a newline after each star.

**Comment by 52bit23** [comment]
How do you add a newline after completing each row?

**Comment by 55bit23** [comment]
Use print() without arguments at the end of the inner loop.

**Comment by 52bit23** [comment]
What happens if the input is 0?

**Comment by 55bit23** [comment]
No rows will be printed, as the loop will not run.

**Comment by 52bit23** [comment]
thank you @55bit23  for providing solution of my questions

**Comment by 11bit23** [comment]
chalo chodo ye sab

**Comment by 11bit23** [comment]
can u play game

**Comment by 11bit23** [comment]
kitna padna hai
